### ISSUE TITLE
Replace filter values or statements - utility

### ISSUE THREAD

**Issue by kirrg001** [NexesJS/NQL#3]
## Requirement

NQL should offer a new interface utility to replace statements.

e.g. i have a filter

`filter=primary_tag:slug`

`primary_tag` could be an alias. As a developer you want to replace this value.
The replacement should either happen on filter level or on statement level. This needs research.

## Tasks

- [ ] collect use cases and list them here
- [ ] come up with a plan how the utility should look like
- [ ] implement

**Comment by kirrg001** [comment]
Inspirtation can be found in GQL: https://github.com/TryGhost/GQL/blob/master/lib/lodash-stmt.js

**Comment by gargol** [comment]
Closing in favor of https://github.com/NexesJS/NQL/issues/2 as it will aggregate all the knowledge around possible statement merging logic.
